# Generated by Django 5.1.6 on 2025-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado')], max_length=50),
        ),
    ]
